### ISSUE TITLE
How to use Redux DevTools?

### ISSUE THREAD

**Issue by comerc** [AdamBrodzinski/meteor-redux-example#5]
...with this example.

[I love Blaze](https://github.com/comerc/meteor-template2). Please help me! :)

**Comment by AdamBrodzinski** [comment]
Redux DevTools are tricky to use... I would suggest starting with a react boilerplate and copy/paste the bits over https://github.com/AdamBrodzinski/basic-redux-example/blob/master/src/index.js

or try
https://github.com/AdamBrodzinski/simple-redux-react

**Comment by comerc** [comment]
https://github.com/AdamBrodzinski/meteor-redux-example/pull/6
